### ISSUE TITLE
Mod Crashes before minecraft starts "java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'pythonmc'!" 

### ISSUE THREAD

**Issue by juice-ix** [RevolvingMadness/PythonMC#1]
In my Minecraft logs, I get this error "java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'pythonmc'!."
I have installed python as well, I don't know what's happening

**Comment by RevolvingMadness** [comment]
did you get this to work?
